networks:
    my_app_db-dev:
        driver: bridge

services:
    my_app:
        container_name: my_app
        image: some.repository.com/my_app_db:latest # need to start using image with already initiliazed database to speed up container startup
        ports:
            - 50032:5432
        networks:
            - my_app_db-dev
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 1s
            timeout: 1s
            retries: 5
            start_period: 10s

    my_app_replica:
        container_name: my_app_replica
        image: some.repository.com/my_app_db:latest # need to start using image with already initiliazed database to speed up container startup
        ports:
            - 50432:5432
        networks:
            - my_app_db-dev
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 1s
            timeout: 1s
            retries: 5
            start_period: 10s
