networks:
    my_app_db-dev:
        driver: bridge

services:
    my_app:
        container_name: my_app
        image: some.repository.com/my_app_db:latest
        ports:
            - 50432:5432
        networks:
            - my_app_db-dev

    my_app_replica:
        container_name: my_app_replica
        image: some.repository.com/my_app_db:latest
        ports:
            - 50032:5432
        networks:
            - my_app_db-dev
